export const PATHS = {
	BASE_URL: '',
	USERS_LIST: 'users-list',
	CHANGE_USER_PASSWORD: 'change-user-password',
	LOGIN: 'login',
	PASSWORD_RECOVERY: 'password-recovery',
	FORGOTTEN_PASSWORD: 'forgotten-password',
	VERIFY_EMAIL: 'verify-email',
	ENABLED_VERIFIED: 'enabled-verified',
	REGISTER: 'register',
	MY_PROFILE: 'my-profile',
	REGISTER:'register',
	HELP:'help',
	WELCOME: 'welcome',
	EMAIL_REGISTER_SENDED: 'email-register-sended',
	MAIN_GOALS: 'main-goals',
	TRAINING_LEVEL: 'training-level',
	WEIGHT_HEIGHT: 'weight-height',
	HELP: 'help',
	CONTACT: 'contact',
};

export const SHOW_NAVBAR = [PATHS.BASE_URL];

export const TOPBAR_TEXTS = {
	[PATHS.BASE_URL]: 'topBar.main',
	[PATHS.USERS_LIST]: 'topBar.usersList',
	[PATHS.CHANGE_USER_PASSWORD]: 'topBar.changeUserPassword',
	[PATHS.LOGIN]: 'topBar.login',
	[PATHS.PASSWORD_RECOVERY]: 'topBar.passwordRecovery',
	[PATHS.FORGOTTEN_PASSWORD]: 'topBar.forgottenPassword',
	[PATHS.VERIFY_EMAIL]: 'topBar.verifyEmail',
	[PATHS.ENABLED_VERIFIED]: 'topBar.enabledVerified',
	[PATHS.REGISTER]: 'topBar.register',
	[PATHS.MY_PROFILE]: 'topBar.myProfile',
	[PATHS.EMAIL_REGISTER_SENDED]:'topBar.emailRegisterSended',
	[PATHS.HELP]: 'topBar.help',
	[PATHS.EMAIL_REGISTER_SENDED]: 'topBar.emailRegisterSended',
	[PATHS.CONTACT]: 'topBar.contact',
};
